### ISSUE TITLE
ipmt throws deprecation warning in numpy 2.0.dev

### ISSUE THREAD

**Issue by pllim** [lmfit/asteval#120]
You can reproduce this using numpy nightly wheel from https://anaconda.org/scientific-python-nightly-wheels/numpy and turning warning into exception.

```
DeprecationWarning: In accordance with NEP 32, the function ipmt was removed from NumPy version 1.20.
A replacement for this function is available in the numpy_financial library: https://pypi.org/project/numpy-financial
```

https://github.com/newville/asteval/blob/b69168cefcd525b466ea0a8fc5fd882781601623/asteval/astutils.py#L175

**Comment by newville** [comment]
@pllim thanks - it looks like there are several others too.  Will investigate and fix.

**Comment by newville** [comment]
This is now fixed in the master branch so that those functions are imported by default from `numpy_financial`, if that package is installed.
