### ISSUE TITLE
Handling NameError is not working

### ISSUE THREAD

**Issue by shazarivf** [lmfit/asteval#129]
We recently upgraded to a new version and we have a several scripts that relied on handling NameError as we couldn't ensure all user_symbols to be present always.
The following is a small example snippet doesn't work as expected anymore.

```
from asteval import Interpreter

aeval = Interpreter(user_symbols={"one": 1, "two": 2, "fallback_var": 0})

code = """
try:
    output = some_var
except NameError:
    output = None
output or fallback_var
"""

a = aeval(code)
```
This results in:
```
NameError
   
try:
    output = some_var
except NameError:
    output = None
output or fallback_var
                 ^^^
name 'some_var' is not defined
```
NameError doesn't get handled and the code just breaks and returns None
It looks like this behavior changed with version 0.9.17 and [this commit](https://github.com/lmfit/asteval/commit/4b99b6b94d71c4c2419b84336eb2bd45ad0e130b).

**Comment by newville** [comment]
@shazarivf Thasnks - I agree that this looks wrong.  I'll need to investigate, and I can't look at this in depth this week and can't promise this will be fixed quickly.

Does undoing that check of `if len(self.error) == 0` fix this?

**Comment by shazarivf** [comment]
@newville yes, removing the check fixes it. I can raise a PR if you think the check is safe to remove

**Comment by newville** [comment]
@shazarivf Yes please -- I'd be interested to see what tests fail!
